### ISSUE TITLE
Can't resolve 'mapbox-gl/dist/mapbox-gl.css'

### ISSUE THREAD

**Issue by jturnerbsky** [bryanwokich/blacksky-map#4]
Repro steps:
- `npm install`
- `npm run`
- Receive an error message `Can't resolve 'mapbox-gl/dist/mapbox-gl.css'`

Environment:
- MacOS 12.2.1
- npm 6.14.10
- node 14.15.4

**Comment by bryanwokich** [comment]
Dang.  Looks like I missed `--save` when installing a node package.
